<a href="https://colab.research.google.com/github/otoperalias/teaching/blob/TallerUTE_AnalisisCuanti/material/censo22/Filtrado_tabla_viviendas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Este notebook importa la tabla de viviendas del censo de 2022 y selecciona la provincia de Loja

#### 1. Descarga de microdatos del Censo de 2022

* En este enlace https://www.censoecuador.gob.ec/data-censo-ecuador/, clicamos en el primer icono de "Base de datos" y luego en "Base de datos CSV" en 2022.  
* Se descarga una carpeta comprimida de 474 Megas. Descomprimimos esta carpeta, que contiene 5 archivos con formato .csv.  
* Subimos a Google Colab el archivo "CPV_Vivienda_2022_Nacional", que pesa 647 megas y por tanto tarda algunos minutos en subirse.

#### 2. Importamos las librerías que vamos a usar en este notebook

In [1]:
import pandas as pd

#### 3. Leemos con ```pandas``` el fichero y lo exploramos

In [6]:
# Leemos el fichero
viv=pd.read_csv("CPV_Vivienda_2022_Nacional.csv", sep=";")

In [7]:
# Mostramos la tabla
viv

,I01,I02,I03,I04,I05,I10,D01,V01,V0201,V0202,...,AUR,CANTON,PARROQ,ID_VIV,TOTFALL,TOTEMI,TOTPER,V0201R,V15R,IMP_VOPA
0,1,1,50,1,1,1,2,1,1.0,NaN,...,1,101,10150,101500010010001,0,0,5,1.0,4.0,2
1,1,1,50,1,1,2,1,2,1.0,NaN,...,1,101,10150,101500010010002,0,0,3,1.0,5.0,2
2,1,1,50,1,1,3,1,1,1.0,NaN,...,1,101,10150,101500010010003,0,0,1,1.0,3.0,2
3,1,1,50,1,1,4,1,1,1.0,NaN,...,1,101,10150,101500010010004,0,1,2,1.0,5.0,2
4,1,1,50,1,1,5,1,1,1.0,NaN,...,1,101,10150,101500010010005,0,0,4,1.0,5.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6611550,24,3,52,999,4,116,7,5,1.0,NaN,...,2,2403,240352,2403529990040116,0,0,3,1.0,4.0,2
6611551,24,3,52,999,4,117,7,5,1.0,NaN,...,2,2403,240352,2403529990040117,0,0,2,1.0,1.0,2
6611552,24,3,52,999,4,118,7,5,1.0,NaN,...,2,2403,240352,2403529990040118,0,0,1,1.0,1.0,2
6611553,24,3,52,999,4,119,4,1,1.0,NaN,...,2,2403,240352,2403529990040119,0,0,1,1.0,3.0,2
6611554,24,3,52,999,4,120,7,5,1.0,NaN,...,2,2403,240352,2403529990040120,0,0,2,1.0,1.0,2

In [8]:
# Vemos que tiene 6.6 millones de registros (!!)

In [9]:
# Listamos las columnas de la tabla
viv.columns

Index(['I01', 'I02', 'I03', 'I04', 'I05', 'I10', 'D01', 'V01', 'V0201',
       'V0202', 'V03', 'V04', 'V05', 'V06', 'V07', 'V08', 'V09', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'AUR', 'CANTON', 'PARROQ',
       'ID_VIV', 'TOTFALL', 'TOTEMI', 'TOTPER', 'V0201R', 'V15R', 'IMP_VOPA'],
      dtype='object')

#### 4. Seleccionamos los registros de Loja


* El archivo "4_DICCIONARIO_DE_VARIABLES_CPV_2022" (disponible [aquí](https://www.censoecuador.gob.ec/data-censo-ecuador/)) indica que, en la tabla de vivienda, la columna I01 hace referencia al código de la provincia.
* El archivo "6.-ANEXO_CLASIFICADORES_NOMENCLATURAS" (disponible también [aquí](https://www.censoecuador.gob.ec/data-censo-ecuador/)) indica que el código de Loja es el 11.

In [11]:
loja=viv.loc[viv['I01']==11].copy()

In [12]:
# Echamos un vistazo a la nueva tabla para Loja, que ahora tiene 199000 registros.
loja

,I01,I02,I03,I04,I05,I10,D01,V01,V0201,V0202,...,AUR,CANTON,PARROQ,ID_VIV,TOTFALL,TOTEMI,TOTPER,V0201R,V15R,IMP_VOPA
3280222,11,1,50,1,1,1,2,2,1.0,NaN,...,1,1101,110150,1101500010010001,0,0,4,1.0,5.0,2
3280223,11,1,50,1,1,2,2,2,1.0,NaN,...,1,1101,110150,1101500010010002,0,0,5,1.0,2.0,2
3280224,11,1,50,1,1,3,2,2,1.0,NaN,...,1,1101,110150,1101500010010003,0,0,4,1.0,2.0,2
3280225,11,1,50,1,1,4,2,1,1.0,NaN,...,1,1101,110150,1101500010010004,0,0,3,1.0,6.0,2
3280226,11,1,50,1,1,5,4,3,1.0,NaN,...,1,1101,110150,1101500010010005,0,0,4,1.0,2.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3479230,11,16,51,999,5,65,7,1,3.0,NaN,...,2,1116,111651,1116519990050065,0,0,0,2.0,NaN,2
3479231,11,16,51,999,5,66,7,1,4.0,NaN,...,2,1116,111651,1116519990050066,0,0,0,3.0,NaN,2
3479232,11,16,51,999,888,1,3,1,1.0,NaN,...,2,1116,111651,1116519998880001,0,0,2,1.0,2.0,2
3479233,11,16,51,999,888,2,3,1,1.0,NaN,...,2,1116,111651,1116519998880002,0,0,4,1.0,2.0,2
3479234,11,16,51,999,888,3,3,1,1.0,NaN,...,2,1116,111651,1116519998880003,0,0,3,1.0,2.0,2

#### 5. Guardamos la tabla en un archivo csv para descargarlo en nuestro ordenador.

In [13]:
loja.to_csv("viv_loja.csv")

En la pestaña de **Archivos** de la izquierda podemos ver la nueva tabla (si no aparece, clicamos en "actualizar").  
Sobre el archivo, clicamos sobre los tres puntos que aparecen a la derecha y seleccionamos descargar.